### ISSUE TITLE
isOfferWallReady method returns always true

### ISSUE THREAD

**Issue by isamotiuc** [AdGem/Android-Example#2]
1) After first call of `showOfferWall`, if we try to call again, we receive error. 
```
09-24 12:40:46.848 4815-4815/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.giftloop, PID: 4815
    java.lang.RuntimeException: Unable to start activity ComponentInfo{co.giftloop/com.adgem.android.internal.offerwall.OfferWallActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4917)
        at android.view.ViewGroup.addView(ViewGroup.java:4748)
        at android.view.ViewGroup.addView(ViewGroup.java:4720)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:449)
        at android.app.Activity.setContentView(Activity.java:2745)
        at com.adgem.android.internal.offerwall.OfferWallActivity.onCreate(Unknown Source:24)
        at android.app.Activity.performCreate(Activity.java:7050)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:6701) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) 
```
Nothing is written about this in documentation, and how properly to start second time offer wall. 
To solve this, we are useing `AdGemCallback`. 

2) `isOfferWallReady` returns always true, doesnt metter was callback `AdGem.STATE_READY` or doesnt. Also if NO internet connection, it also returns true. 

This is our implementation [link](https://gist.github.com/isamotiuc/e6ab7f4dcdded047d09a938668ff08f6), but we still receive error that I provided above. The question is, when will be fixed `isOfferWallReady` or may be you have some suggestions how to fix it.

**Comment by Exaper** [comment]
@isamotiuc thanks for report. We are looking into this.

**Comment by isamotiuc** [comment]
@Exaper Thank you!
FYI: I just tried new 0.9.2, the same result. `isOfferWallReady` always returns true.

**Comment by Exaper** [comment]
@isamotiuc while we are preparing a fix, please make sure to call `showOfferWall` only once and ignore `isReady` flag for now.

**Comment by Exaper** [comment]
@isamotiuc we've released v0.9.3 which should not crash when launching Offer Wall for the second time. Also note that network availability will not affect state of the Offer Wall. We are still investigating potential implications of accounting for it.

**Comment by isamotiuc** [comment]
@Exaper Yes, bug was fixed. Thank You!

About network, if user will open offer wall without internet, will be opened not loaded WebView.
Then if he will close offerwall and connect internet, and if he will try to open it again, already **with** Internet, he will see again the same not loaded WebView.

But this is not so critical then this cash.

**Comment by Exaper** [comment]
@isamotiuc thanks for the feedback. We are looking into it.

**Comment by isamotiuc** [comment]
@Exaper Hello, we still receive such error on version `0.9.3`
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
       at com.adgem.android.internal.offerwall.OfferWall.a(Unknown Source)
       at com.adgem.android.internal.offerwall.OfferWall.a(Unknown Source)
       at com.adgem.android.internal.offerwall.OfferWallActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6904)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3269)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3418)
       at android.app.ActivityThread.access$1100(ActivityThread.java:231)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
But in much smaller amount, just for 0.5% percent of users. But it is second from top in our dashbord.
Do you have chnage log for `0.9.4`, was this issue fixed there?

**Comment by Exaper** [comment]
@isamotiuc thanks for this report. The issue is not related to original problem. We are tracking it with https://github.com/AdGem/Android-Example/issues/3

**Comment by Exaper** [comment]
@isamotiuc Please upgrade to AdGem v0.9.5. If the issue persists, drop a note in https://github.com/AdGem/Android-Example/issues/3. Thanks a lot for your help!
